template: |
  ## Changelog

  $CHANGES
name-template: 'KNG v$RESOLVED_VERSION'
#tag-template: 'v$RESOLVED_VERSION'
no-changes-template: '### Nothing included yet'
change-template: '- $TITLE [PR #$NUMBER]'
categories:
  - title: 'New and improved Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Other changes'
    labels:
      - 'misc'
  - title: 'Dependency updates'
    labels:
      - 'dependencies::major'
      - 'dependencies::minor'
      - 'dependencies::patch'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'enhancement'
  default: patch
replacers:
# resolving/closing keywords
  - search: '/(close(s|d)?|fix(es|ed)?|resolve(s|d)?)\s*#\d*:?/gi'
    replace: ''
# direct issue references
  - search: '/issue\W+#?\d+[ :]?\W+/gi'
    replace: ''
