name: Label PRs

on:
  pull_request:
    types:
      - opened
      - unlabeled

jobs:
  label_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Put issue labels on their PRs
        uses: nmoral/github-action-label-pull-request@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
