name: Label PRs

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
    types:
      - opened

jobs:
  label_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Put issue labels on their PRs
        uses: nmoral/github-action-label-pull-request@v1.0.0
        with:
          clean-before-fetching: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
