name: Report test coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  report-coverage:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn -B -U test jacoco:report
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/target/**/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 75
        min-coverage-changed-files: 80
        continue-on-error: false
        update-comment: true
        title: "Test coverage report"
        pass-emoji: ":green_circle:"
    - name: Fail if overall coverage is less than 75%
      if: ${{ steps.jacoco.outputs.coverage-overall < 75.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 75%!')
    - name: Fail PR if coverage of changed code is less than 80%
      if: ${{ GITHUB_REF != master && steps.jacoco.outputs.coverage-changed-files < 80.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Coverage of changed code is less than 80%!')
