name: Report test coverage

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn -B -U test jacoco:report
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/target/**/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 75
        min-coverage-changed-files: 80
        update-comment: true
        title: "Test coverage report"
        pass-emoji: ":green_circle:"
